WW-47 changed default map to custom map.
TomFaust/Medialab-Interactive_map pull request #5
Opened 2022-03-29 15:03 UTC by Qwinsie

![image](https://user-images.githubusercontent.com/53104056/160637314-2656fcb5-a436-4380-a2f9-d163e146297a.png)

2022-03-29 15:48 UTC, NiekRottier approved these changes, later dismissed
Zouden we nu allemaal jouw API key moeten gebruiken, aangezien deze kaart style van jou is?
EDIT: Lm, volgens mij niet

2022-03-29 22:05 UTC, NiekRottier requested changes
Mapbox werkt niet bij mij met deze style. Ik gok dat we de API key nodig hebben van de creator van de style (Quincy). Of misschien kan je een setting aanpassen waar je de style heb gemaakt?
ERR index.js:29:
GET https://api.mapbox.com/styles/v1/qwinsie/cl1c6rl09007n14pk10egyijf?access_token=pk.eyJ1Ijoibmlla2plIiwiYSI6ImNraHhhZnd6aDBnbTEzM2xmY2d4bjl4ZTgifQ.JPGfWisi_idnva1vlndOPA 404 (Not Found)

2022-03-30 10:42 UTC, Qwinsie commented
@NiekRottier I made the style public. Could you please check again for me if it is available?

2022-03-30 12:03 UTC, NiekRottier approved these changes

2022-03-30 12:04 UTC, merged